config/routes.rb
Rails.application.routes.draw do
  mount Faalis::Engine => '/'

  api_routes do
  end

  in_dashboard do
  end

  resources :galleries
  resources :tests
  get 'about_us', to: 'about_us#index', as: :about_us
  get 'contact_us', to: 'contact_us#index', as: :contact_Us

  root  "wellcom#index"

  get '/resume' => 'about_us#resume'

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "sahandm96@hotmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
end

app/models/test.rb
class Test < ActiveRecord::Base
end

app/controllers/about_us_controller.rb
class AboutUsController < ApplicationController
  def index

  end
end

app/controllers/api_controller.rb
class APIController < Faalis::APIController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  extend Faalis::I18n::Locale
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contact_us_controller.rb
class ContactUsController < ApplicationController
  def index
    def new
        @contact = Contact.new
      end

      def create
        @contact = Contact.new(params[:contact])
        @contact.request = request
        if @contact.deliver
          flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
        else
          flash.now[:error] = 'Cannot send message.'
          render :new
        end
      end
  end
end

app/controllers/dashboard/application_controller.rb
class Dashboard::ApplicationController < Faalis::Dashboard::ApplicationController

  def setup_sidebar
    @sidebar = sidebar(t('faalis.engine_name')) do |s|
      s.faalis_entries

      # Put your sidebar entries in here like this:
      #
      # s.menu(title, icon: 'fa fa-book') do
      #   s.item(title,
      #          url: main_app.dashboard_books_path,
      #          model: 'Book')
      # end
      #
      # For more information take a look at `sidebar` section of Faalis guides.
    end
  end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :set_gallery, only: [:show, :edit, :update, :destroy]

  # GET /galleries
  # GET /galleries.json
  def index
    @galleries = Gallery.all
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
  end

  # GET /galleries/new
  def new
    @gallery = Gallery.new
  end

  # GET /galleries/1/edit
  def edit
  end

  # POST /galleries
  # POST /galleries.json
  def create
    @gallery = Gallery.new(gallery_params)

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to @gallery, notice: 'Gallery was successfully created.' }
        format.json { render :show, status: :created, location: @gallery }
      else
        format.html { render :new }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /galleries/1
  # PATCH/PUT /galleries/1.json
  def update
    respond_to do |format|
      if @gallery.update(gallery_params)
        format.html { redirect_to @gallery, notice: 'Gallery was successfully updated.' }
        format.json { render :show, status: :ok, location: @gallery }
      else
        format.html { render :edit }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @gallery.destroy
    respond_to do |format|
      format.html { redirect_to galleries_url, notice: 'Gallery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gallery
      @gallery = Gallery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gallery_params
      params[:gallery]
    end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :set_test, only: [:show, :edit, :update, :destroy]

  # GET /tests
  # GET /tests.json
  def index
    @tests = Test.all
  end

  # GET /tests/1
  # GET /tests/1.json
  def show
  end

  # GET /tests/new
  def new
    @test = Test.new
  end

  # GET /tests/1/edit
  def edit
  end

  # POST /tests
  # POST /tests.json
  def create
    @test = Test.new(test_params)

    respond_to do |format|
      if @test.save
        format.html { redirect_to @test, notice: 'Test was successfully created.' }
        format.json { render :show, status: :created, location: @test }
      else
        format.html { render :new }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tests/1
  # PATCH/PUT /tests/1.json
  def update
    respond_to do |format|
      if @test.update(test_params)
        format.html { redirect_to @test, notice: 'Test was successfully updated.' }
        format.json { render :show, status: :ok, location: @test }
      else
        format.html { render :edit }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tests/1
  # DELETE /tests/1.json
  def destroy
    @test.destroy
    respond_to do |format|
      format.html { redirect_to tests_url, notice: 'Test was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test
      @test = Test.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def test_params
      params.require(:test).permit(:post)
    end
end

app/controllers/wellcom_controller.rb
class WellcomController < ApplicationController
  def index
    
  end
end

app/helpers/about_us_helper.rb
module AboutUsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_us_helper.rb
module ContactUsHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/wellcom_helper.rb
module WellcomHelper
end

app/views/about_us/Resume.html.erb
<h1>AboutUs#Resume</h1>
<p>Find me in app/views/about_us/Resume.html.erb</p>

app/views/about_us/index.html.erb
<h1>AboutUs#About-Us</h1>
<p>Find me in app/views/about_us/About-Us.html.erb</p>

app/views/contact_us/creat.html.erb
<div>
  <% flash.each do |key, value| %>
    <div>
      <a href="#" data-dismiss="alert">×</a>
        <%= value %>
    </div>
  <% end %>
</div>

app/views/contact_us/index.html.erb
<div align="center">
  <h3>Send A message to Us</h3>

  <%= simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f| %>
    <%= f.input :name, :required => true %>
    <%= f.input :email, :required => true %>
    <%= f.input :message, :as => :text, :required => true %>
    <div class= "hidden">
      <%= f.input :nickname, :hint => 'Leave this field blank!' %>
    </div>
    <div>
      </br>
      <%= f.button :submit, 'Send message', :class=> "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/galleries/_form.html.erb
<%= form_for(@gallery) do |f| %>
  <% if @gallery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>

      <ul>
      <% @gallery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/galleries/edit.html.erb
<h1>Editing Gallery</h1>

<%= render 'form' %>

<%= link_to 'Show', @gallery %> |
<%= link_to 'Back', galleries_path %>

app/views/galleries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Galleries</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @galleries.each do |gallery| %>
      <tr>
        <td><%= link_to 'Show', gallery %></td>
        <td><%= link_to 'Edit', edit_gallery_path(gallery) %></td>
        <td><%= link_to 'Destroy', gallery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gallery', new_gallery_path %>

app/views/galleries/new.html.erb
<h1>New Gallery</h1>

<%= render 'form' %>

<%= link_to 'Back', galleries_path %>

app/views/galleries/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_gallery_path(@gallery) %> |
<%= link_to 'Back', galleries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="Style.css">
  <title>.::MARTA::.</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
  <header>
    <nav class="HearderBox">
    <div id="LOGO" class="HeaderBox">
        <%= image_tag("ablogo1.png") %>
    </div>
      <ul>
        <li><%= link_to("Contact Us",contact_Us_path)%></li>
        <li><%= link_to("About us", about_us_path)%></li>
        <li><%= link_to("Gallery", galleries_path)%></li>
        <li><%= link_to("Home",root_path)%></li>
      </ul>

   </nav>
</header>
<div id="MainPage">


<%= yield %>
</div>
<footer>
  <div id="Ab">
    <%= image_tag("ablogo1.png") %>
    <%= image_tag("ablogo2.png") %>
    <%= image_tag("ablogo1.png") %>
    <%= image_tag("ablogo2.png") %>
    <%= image_tag("ablogo1.png") %>
  </div>
  <p dir="rtl">
    تمام حقوق مادی و معنوی این وبسایت مطعلق به شرکت ستاره خرد می باشد.
  </p>
</footer>
</body>
</html>

app/views/wellcom/index.html.erb
<div id="cf7" class="shadow">
  <%= image_tag "0001.jpg" , :class => "opaque"  %>
  <%= image_tag "0002.jpg"  %>
  <%= image_tag "0003.jpg"  %>
  <%= image_tag "0004.jpg"  %>
</div>
<p id="cf7_controls">
  <span class="selected">Image 1</span>
  <span>Image 2</span>
  <span>Image 3</span>
  <span>Image 4</span>
</p>